# Base image
FROM python:3.7
#-alpine3.16

# Running every next command wih this user
USER root
EXPOSE 8501

# Creating work directory in docker
WORKDIR /app

# Copying files to docker
COPY . '/app'
# Installing requirements
RUN pip3 install -r requirements.txt

# Starting application
CMD streamlit run frontend.py
